version: '3.3'

services:
  traefik:
    image: traefik:2.5
    restart: always
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.network=web
      - --providers.file.watch=true
      - --providers.file.filename=/etc/traefik/proxy-config.toml
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - "--providers.docker.exposedbydefault=false"
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --experimental.plugins.traefik-cors.modulename=github.com/quintinheard/traefik-cors
      - --experimental.plugins.traefik-cors.version=v0.1.0
      #- --experimental.plugins.traefik-plugin-cors.modulename=github.com/pxxonline/traefik-plugin-cors
      #- --experimental.plugins.traefik-plugin-cors.version=v0.1.7
      - --pilot.token=f58037b3-3aae-4877-9369-046415d3e177
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
      - ./log:/log
      - ./letsencrypt:/letsencrypt
      - ./proxy-config.toml:/etc/traefik/proxy-config.toml:ro
    container_name: traefik

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2.2.0-arm
    secrets:
      - source: traefik-forward-auth-secrets
        target: /config
    command:
      - --match-whitelist-or-domain
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - PROVIDERS_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SECRET=${SECRET}
      - LOG_LEVEL=debug
      - CONFIG=/config
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
    container_name: oauth_traefik

secrets:
  traefik-forward-auth-secrets:
    file: ./secrets/traefik-forward-auth

networks:
  web:
    external: true